= Local Development Environment
:toc:
:caution-caption: ☠
:important-caption: ❗
:note-caption: 🛈
:tip-caption: 💡
:warning-caption: ⚠
ifdef::env-github[]
rendered by GitHub Asciidoctor {asciidoctor-version}.
endif::[]
ifndef::env-github[]
rendered by Asciidoctor {asciidoctor-version}
endif::[]


== Overview

This documentation should help you to setup a local k8s environment.


== Linux asdf-vm setup

If you are a linux user you ease your setup effort by using asdf.


[source,bash]
----

./initAsdf-vm.sh

----



== Local Kubernetes


=== Requirements

==== Mandatory tools
* Install kind cli and make it available in your PATH https://github.com/kubernetes-sigs/kind
* Install kubectl and make it available in your PATH https://kubernetes.io/docs/tasks/tools/
* Install kustomize and make it available in your PATH https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/
* Install helm and make it available in your PATH https://helm.sh/docs/intro/install/

[TIP]
.optional: kind autocompletion for zsh
====

[source,bash]
----
source <(kind completion zsh)
----

====

==== Optional tools


===== k9s

Terminal based UI to interact with your Kubernetes clusters.

<https://k9scli.io/>


``


=== K8s Setup

Setup K8s Cluster

* Setup K8s and update kubectl config
* Install Ingress (nginx / traefik)
* Install Metriks Server

.Start the k8s cluster
[source,bash]
----

./kind/shell-based-setup/localK8s.sh

----

.Reset / restart the cluster
[source,bash]
----

./kind/shell-based-setup/localK8s.sh -r

----

### Verify k8s setup

.Verify kubectl context is updated
[source,bash]
----
$ kubectl config current-context
kind-k8s-playground
----

.Verify pods are running
[source,bash]
----
$ kubectl get pods -A
NAMESPACE            NAME                                                   READY   STATUS    RESTARTS   AGE
demo                 helloweb-67dffcd76f-s8mq2                              1/1     Running   0          40m
ingress-nginx        ingress-nginx-controller-5dff8dcf67-f4qz6              1/1     Running   0          40m
kube-system          coredns-6d4b75cb6d-r7cbn                               1/1     Running   0          41m
kube-system          coredns-6d4b75cb6d-zpgtw                               1/1     Running   0          41m
kube-system          etcd-k8s-playground-control-plane                      1/1     Running   0          41m
kube-system          kindnet-hgpw8                                          1/1     Running   0          41m
kube-system          kube-apiserver-k8s-playground-control-plane            1/1     Running   0          41m
kube-system          kube-controller-manager-k8s-playground-control-plane   1/1     Running   0          41m
kube-system          kube-proxy-crjww                                       1/1     Running   0          41m
kube-system          kube-scheduler-k8s-playground-control-plane            1/1     Running   0          41m
kube-system          metrics-server-555c8cbc74-smnbx                        1/1     Running   0          41m
local-path-storage   local-path-provisioner-9cd9bd544-x4h62                 1/1     Running   0          41m
----


.Verify metrics are available
[source,bash]
----
$ kubectl top nodes
NAME                           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
k8s-playground-control-plane   228m         2%     677Mi           2%
----


.Verify demo application is responding properly
[source,bash]
----
$ curl http://localhost:48080/demo/hello
Hello, world!
Version: 1.0.0
Hostname: helloweb-67dffcd76f-s8mq2

$ curl -k https://localhost:48443/demo/hello
Hello, world!
Version: 1.0.0
Hostname: helloweb-67dffcd76f-s8mq2

----



## Remove / uninstall k8s

* Removes the whole k8s cluster
* Stops all containers
* Removes the created container registry

.Reset / restart the cluster
[source,bash]
----

./kind/shell-based-setup/localK8s.sh -d

----
If you want to remove everything, like docker network or stored images call, consider calling:

```bash

docker container prune
docker network prune
docker system prune
docker volume prune
docker builder prune
```

## Activate kubectl autocompletion

check according to your terminal <https://kubernetes.io/docs/tasks/tools/included/>

Activate for zsh

```bash
source <(kubectl completion zsh)
```

Sample Usage

```bash
kubectl -n local get po [Press 'TAB']
```

## Kind Troubleshooting

Query Container Reqistry for all images

```bash
curl -s "http://localhost:5003/v2/_catalog" | jq
{
  "repositories": [
    "my-backend",
    "my-security",
    "my-service",
    "my-workflow"
  ]
}

```

Query tags for a specific image

```bash
curl -s "http://localhost:5003/v2/$MY_IMAGE_NAME/tags/list" | jq
```

Query image information for a specific image and tag

```bash
curl -s "http://localhost:5003/v2/$MY_IMAGE_NAME/manifests/$TAG_NAME" | jq
```




### Free diskspace


Sometimes its necessary to remove all images from the container registry.

[source,bash]
----
./kind/shell-based-setup/clearContainerRegistry.sh
----


Free diskspace by clean up docker
[source,bash]
----
docker images | grep '3 weeks ago' | awk '{print $1 ":" $2}' | xargs -n 1 docker rmi
docker system prune
docker image prune
docker volume prune
----